import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-construction-retainage-lien-release-recovery",
  "engine": "recovery",
  "title": "Construction Retainage & Lien Release Recovery",
  "shortTitle": "Construction Retainage and Lien Release Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through construction retainage & lien release recovery",
  "industry": "Construction Cash Recovery",
  "uiPort": 4598,
  "apiPort": 5598,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Construction Retainage & Lien Release Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "collectedAmount",
    "expectedKey": "earnedAmount",
    "actualLabel": "Retainage Collected",
    "expectedLabel": "Earned Retainage Due",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Construction Retainage & Lien Release Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("contract-and-subcontract-library","CRL01","Contract and subcontract library","Execute contract and subcontract library using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed contract and subcontract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Contract and subcontract library Reference","text","CRL01-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("schedule-of-values-ingestion","CRL02","Schedule-of-values ingestion","Execute schedule-of-values ingestion using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed schedule-of-values ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Schedule-of-values ingestion Reference","text","CRL02-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("pay-application-reconciliation","CRL03","Pay-application reconciliation","Execute pay-application reconciliation using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed pay-application reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Pay-application reconciliation Reference","text","CRL03-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("retainage-calculation","CRL04","Retainage calculation","Execute retainage calculation using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed retainage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Retainage calculation Reference","text","CRL04-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("substantial-completion-tracking","CRL05","Substantial completion tracking","Execute substantial completion tracking using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed substantial completion tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Substantial completion tracking Reference","text","CRL05-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("punch-list-evidence","CRL06","Punch-list evidence","Execute punch-list evidence using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed punch-list evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Punch-list evidence Reference","text","CRL06-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("change-order-linkage","CRL07","Change-order linkage","Execute change-order linkage using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed change-order linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Change-order linkage Reference","text","CRL07-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("conditional-waiver-management","CRL08","Conditional waiver management","Execute conditional waiver management using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed conditional waiver management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Conditional waiver management Reference","text","CRL08-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("unconditional-waiver-management","CRL09","Unconditional waiver management","Execute unconditional waiver management using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed unconditional waiver management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Unconditional waiver management Reference","text","CRL09-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("preliminary-notice-deadlines","CRL10","Preliminary notice deadlines","Execute preliminary notice deadlines using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed preliminary notice deadlines decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Preliminary notice deadlines Reference","text","CRL10-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("lien-deadline-control","CRL11","Lien deadline control","Execute lien deadline control using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed lien deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Lien deadline control Reference","text","CRL11-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("surety-bond-support","CRL12","Surety bond support","Execute surety bond support using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed surety bond support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Surety bond support Reference","text","CRL12-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("retainage-demand-package","CRL13","Retainage demand package","Execute retainage demand package using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed retainage demand package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Retainage demand package Reference","text","CRL13-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("collection-workflow","CRL14","Collection workflow","Execute collection workflow using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed collection workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Collection workflow Reference","text","CRL14-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]}),
feature("project-cash-forecasting","CRL15","Project cash forecasting","Execute project cash forecasting using prime contracts, subcontracts, schedules of values, pay applications, retainage terms, completion milestones, punch lists, change orders, waivers, notices, liens, bonds, and payments.","Produce a governed project cash forecasting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Contract","text","Project / Contract · Standard Case"],["caseReference","Project cash forecasting Reference","text","CRL15-2026-001"],["collectedAmount","Retainage Collected","currency",549500],["earnedAmount","Earned Retainage Due","currency",648410],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"collectedAmount",subjects:["Contract and subcontract library case","Schedule-of-values ingestion case","Pay-application reconciliation case","Retainage calculation case","Substantial completion tracking case"]})
]);
